/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package logikol;


import Gates.AND;
import Gates.BasicGate;
import Gates.NOT;
import Gates.OR;
import Gates.Node;
import UIObjects.ANDGateObject;
import UIObjects.IONode;
import UIObjects.InputObject;
import Gates.CompoundGate;
import Gates.Input;
import Gates.BasicGateMultiIn;
import Gates.BasicGateSingleIn;

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.control.Button;
import javafx.scene.effect.Effect;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.paint.Paint;

import javafx.scene.shape.Circle;

public class App extends Application {

    int width = 1280;
    int height = 720;

    @Override
    public void start(Stage stage) {

        Group root = new Group();

        Input input1 = new Input(false);
        Input input2 = new Input(true);

        System.out.println("lol");



        InputObject input1UI = new InputObject(root, input1, new IONode(root), 50, 70);
        InputObject input2UI = new InputObject(root, input2, new IONode(root), 200, 300);

        Image imageAND = new Image("gates6-and.png");
        Image imageOR = new Image("gates3-or.png");
        Image imageNOT = new Image("gates3-not.png");


        ANDGateObject andGateUI1 = new ANDGateObject(root, new AND(), new IONode(root), new ImageView(imageAND), 300, 300);
      
        System.out.println(input1UI.getOutNode().getGate());
        Scene scene = new Scene(root, width, height);
        scene.setFill(Color.WHITE);
        stage.setScene(scene);

        
       
        stage.show();
    }

    public static void main(String[] args) {
        launch();
        

    }
}
